workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always


stages:
  - lint
  - page_checks
  - location_test


lint:
  stage: lint
  image: python:3.8
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: on_success
  script:
    - apt-get update; apt-get -y install python3-pip
    - pip install tox
    - tox -e lint

.setup-env: &setup-env
    - apt-get update
    - apt-get install -y unzip curl software-properties-common  vim git python3-pip python3
    - curl https://dl-ssl.google.com/linux/linux_signing_key.pub -o /tmp/google.pub
    - cat /tmp/google.pub | apt-key add -
    - echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google.list
    - mkdir -p /usr/share/desktop-directories
    - wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_92.0.4515.107-1_amd64.deb && apt install -y /tmp/chrome.deb && rm /tmp/chrome.deb
    - apt-get -y update && apt-get install -y google-chrome-stable
    - dpkg-divert --add --rename --divert /opt/google/chrome/google-chrome.real /opt/google/chrome/google-chrome
    - echo -e "#!/bin/bash\nexec /opt/google/chrome/google-chrome.real --no-sandbox --disable-setuid-sandbox \"\$@\"" > /opt/google/chrome/google-chrome
    - chmod 755 /opt/google/chrome/google-chrome
    - google-chrome --version
    - wget https://chromedriver.storage.googleapis.com/92.0.4515.43/chromedriver_linux64.zip && unzip chromedriver_linux64.zip
    - export PATH=`pwd`:${PATH}
    - pip install -r requirements.txt
    - pip install -i https://bbpteam.epfl.ch/repository/devpi/simple .


check_pages_sscx:
  stage: page_checks
  rules:
    - if: $PIPELINE_SELECT == "weekly"
  image: python:3.8-buster
  script:
    - *setup-env
    - exit_code=0
    - pagechecker  --folder resources/SSCX_Portal/  --domain "https://bbp.epfl.ch/sscx-portal/" -H "Authorization:Basic c3NjeDphZXc0b29TaA==" -n 5 || exit_code=1
    - slack_reporter --ok_url $SLACK_LINK_OK --err_url $SLACK_LINK_NOK --name "SSCX Page Check" --filename pagechecker.log --status $exit_code

check_pages_hippocampus:
  stage: page_checks
  rules:
    - if: $PIPELINE_SELECT == "weekly"
  image: python:3.8-buster
  script:
    - *setup-env
    - exit_code=0
    - pagechecker  --folder resources/HIPPO_Portal/  --domain "https://www.hippocampushub.eu/" -n 5 || exit_code=1
    - slack_reporter --ok_url $SLACK_LINK_OK --err_url $SLACK_LINK_NOK --name "HIPPO Page Check" --filename pagechecker.log --status $exit_code

check_dom_sscx:
  stage: page_checks
  rules:
    - if: $PIPELINE_SELECT == "weekly"
  image: python:3.8-buster
  script:
    - *setup-env
    - exit_code=0
    - page_dom_check -n 5 -p resources/sscx_dom_check.json || exit_code=1
    - slack_reporter --ok_url $SLACK_LINK_OK --err_url $SLACK_LINK_NOK --name "SSCX Dom Check" --filename page_dom_check.log --status $exit_code

check_dom_hippo:
  stage: page_checks
  rules:
    - if: $PIPELINE_SELECT == "weekly"
  image: python:3.8-buster
  script:
    - *setup-env
    - exit_code=0
    - page_dom_check -n 5 -p resources/hippo_dom_check.json -d https://www.hippocampushub.eu || exit_code=1
    - slack_reporter --ok_url $SLACK_LINK_OK --err_url $SLACK_LINK_NOK --name "HIPPO Dom Check" --filename page_dom_check.log --status $exit_code

check_links:
  stage: page_checks
  rules:
    - if: $PIPELINE_SELECT == "weekly"
  image: python:3.8-buster
  variables:
    page: "https://portal.bluebrain.epfl.ch/"
  script:
    # Install required packages
    - pip install beautifulsoup4 pylinkvalidator click requests
    - pip install -i https://bbpteam.epfl.ch/repository/devpi/simple .
    - export http_proxy=http://bbpproxy.epfl.ch:80/
    - export https_proxy=http://bbpproxy.epfl.ch:80/
    - export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
    # perform the check
    - exit_code=0
    - pylinkvalidate.py -d 0 -o linkreport.txt -P $page || exit_code=$?
    # and create the report to slack
    - python validate_converter.py linkreport.txt > report.txt
    - slack_reporter --ok_url $SLACK_LINK_OK --err_url $SLACK_LINK_NOK --name "BBP Portal Links" --filename report.txt --status $exit_code

location_testing_sscx:
  stage: location_test
  rules:
    - if: $PIPELINE_SELECT == "daily1"
  image: python:3.8-buster
  script:
    - pip install click requests
    - pip install -i https://bbpteam.epfl.ch/repository/devpi/simple .
    - location_test -p resources/perf_sscx.json --portal sscx

location_testing_hippo:
  stage: location_test
  rules:
    - if: $PIPELINE_SELECT == "daily2"
  image: python:3.8-buster
  script:
    - pip install click requests
    - pip install -i https://bbpteam.epfl.ch/repository/devpi/simple .
    - location_test -p resources/perf_hippo.json --portal hippo

check_mooc:
  stage: page_checks
  rules:
    - if: $PIPELINE_SELECT == "daily"
  image: python:3.8-buster
  script:
    - *setup-env
    - export http_proxy=http://bbpproxy.epfl.ch:80/
    - export https_proxy=http://bbpproxy.epfl.ch:80/
    - export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
    - exit_code=0
    - check_mooc -t resources/Mooc/mooc_tests.json --headless || exit_code=1
    - slack_reporter --ok_url $SLACK_LINK_OK --err_url $SLACK_LINK_NOK --name "MOOC Check" --filename mooc_results.txt --status $exit_code
