
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

stages:
  - lint
  - page_checks


lint:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: on_success
  script:
    - make lint


# check_portal:
#   stage: page_checks
#   variables:
#     SLACK_HOOK: https://hooks.slack.com/services/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
#   script:
#     - echo "check portal"
#     - apt update
#     - apt install -y curl
#     - "curl -X POST $SLACK_HOOK -d \"{'text': 'Just a test', 'icon_emoji':':frog:', 'username': 'SSCX Check'}\""
#     # - python -V
#     # - pip install --upgrade pip setuptools wheel
#     # - pip install -r requirements.txt
#     # - python test_code.py


check_sscx:
  stage: page_checks
  image: python:3.8-buster
  script:
    - apt-get update
    - apt-get install -y unzip curl software-properties-common  vim git python3-pip python3
    - curl https://dl-ssl.google.com/linux/linux_signing_key.pub -o /tmp/google.pub
    - cat /tmp/google.pub | apt-key add -
    - rm /tmp/google.pub
    - echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google.list
    - mkdir -p /usr/share/desktop-directories
    - apt-get -y update && apt-get install -y google-chrome-stable
    - dpkg-divert --add --rename --divert /opt/google/chrome/google-chrome.real /opt/google/chrome/google-chrome
    - echo -e "#!/bin/bash\nexec /opt/google/chrome/google-chrome.real --no-sandbox --disable-setuid-sandbox \"\$@\"" > /opt/google/chrome/google-chrome
    - chmod 755 /opt/google/chrome/google-chrome
    - google-chrome --version
    - pip install -r requirements.txt
    - export PATH=`pwd`/bin:${PATH}
    #- python test_code.py
    - python pagechecker.py  --folder resources/SSCX_Portal/  --domain "https://bbp.epfl.ch/sscx-portal/" -H "Authorization:Basic c3NjeDphZXc0b29TaA==" -n 5

