include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml


stages:
  - lint
  - page_checks


# check_sscx:
#   stage: page_checks
#   tags:
#     - bb5_user
#   variables:
#     bb5_account: proj30
#     bb5_memory: 20G
#     bb5_duration: "15:00"
#     bb5_ntasks: 1
#     bb5_cpus_per_task: 4
#   script:
#     - module load unstable python
#     - python -mvenv venv
#     - source venv/bin/activate
#     - pip install --upgrade pip setuptools wheel
#     - pip install -r requirements.txt
#     - python -V
#     - 'echo "check sscx"'
#     - python test_code.py


check_portal:
  stage: page_checks
  variables:
    IMAGE_PROD: docker-registry-default.ocp.bbp.epfl.ch/bbp-ou-nse/selenium-test-prod
  script:
    - docker pull ${IMAGE_PROD}
    - docker run --rm ${IMAGE_PROD}
    # - apt-get update; apt-get -y install python3-pip python3
    # - 'echo "check potal"'
    # - python -V
    # - pip install --upgrade pip setuptools wheel
    # - pip install -r requirements.txt
    # - python test_code.py


check_docker:
  stage: page_checks
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    CI_REGISTRY_IMAGE: $CI_REGISTRY/bbp-ou-nse/python-test
    CI_COMMIT_TAG: test
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --dockerfile Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - python -V
    - ls
    # - apt-get update
    # - apt-get install -y unzip curl software-properties-common  vim git  
    # - curl https://dl-ssl.google.com/linux/linux_signing_key.pub -o /tmp/google.pub
    # - cat /tmp/google.pub | apt-key add -
    # - rm /tmp/google.pub
    # - echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google.list
    # - mkdir -p /usr/share/desktop-directories
    # - apt-get -y update && apt-get install -y google-chrome-stable
    # - dpkg-divert --add --rename --divert /opt/google/chrome/google-chrome.real /opt/google/chrome/google-chrome
    # - echo "#!/bin/bash\nexec /opt/google/chrome/google-chrome.real --no-sandbox --disable-setuid-sandbox \"\$@\"" > /opt/google/chrome/google-chrome
    # - chmod 755 /opt/google/chrome/google-chrome
    - google-chrome --version

#    - pip install -r requirements.txt
#    - export PATH=`pwd`/bin:$PATH
#    - python test_code.py

