

stages:
  - lint
  - page_checks


check_sscx:
  stage: page_checks
  script:
    - 'echo "check sscx"'
    - python pagechecker.py  --folder resources/SSCX_Portal/  --domain "https://bbp.epfl.ch/sscx-portal/" -H "Authorization:Basic c3NjeDphZXc0b29TaA==" -n 5


check_portal:
  stage: page_checks
  tags:
    - bb5_user
  variables:
    bb5_account: proj30
    bb5_memory: 20G
    bb5_duration: "15:00"
    bb5_ntasks: 1
    bb5_cpus_per_task: 4
  script:
    - module load unstable python
    - python -V
    - 'echo "check potal"'
    - pwd
    - ls