

stages:
  - lint
  - page_checks


check_sscx:
  stage: page_checks
  tags:
    - bb5_user
  variables:
    bb5_account: proj30
    bb5_memory: 20G
    bb5_duration: "15:00"
    bb5_ntasks: 1
    bb5_cpus_per_task: 4
  script:
    - module load unstable python
    - python -mvenv venv
    - source venv/bin/activate
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt
    - python -V
    - 'echo "check sscx"'
    - python test_code.py


check_portal:
  stage: page_checks
  script:
    - apt-get update; apt-get -y install python3-pip python3
    - 'echo "check potal"'
    - python -V
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt
    - python test_code.py


check_docker:
  stage: page_checks
  image: python:3.8-buster
  script:
    - python -V
    - apt-get install chromium-browser
    - google-chrome --version
    - pip install -r requirements.txt
    - export PATH=`pwd`/bin:$PATH
    - python test_code.py

